### ISSUE TITLE
error:The needed function (mex_assess_one_sel) not found. Have you built the package properly?

### ISSUE THREAD

**Issue by sszzy0317** [jponttuset/mcg#19]
when I run the file of install.m. I got the error of The needed function (mex_assess_one_sel) not found. Have you built the package properly? but I have already run the file of build.m.

**Comment by jponttuset** [comment]
Which operating system? Did build.m give any error?
Please consider using COB as it's faster and better.

**Comment by ahappycutedog** [comment]
> 
> 
> Which operating system? Did build.m give any error?
> Please consider using COB as it's faster and better.

i have the same problem.  when i run the build.m in windows, i got the error:
Error using mex
mex_assess_one_sel.cpp
D:\mcg\pre-trained\src\cands\mex_assess_one_sel.cpp(16): fatal error C1083: 无法打开包括文件:
“matlab_multiarray.hpp”: No such file or directory

出错 build (line 66)
    eval(['mex ''' build_file{ii} ''' -outdir ''' fullfile(mcg_root, 'lib') '''' include_str])

What should I do？

**Comment by jponttuset** [comment]
As highlighted on the README, this code is not compatible with Windows.
I would suggest using COB (https://github.com/kmaninis/COB)

**Comment by ahappycutedog** [comment]
> 
> 
> As highlighted on the README, this code is not compatible with Windows.
> I would suggest using COB (https://github.com/kmaninis/COB)

I also run it on Ubuntu 16.04,  but there are some errors:
WARNING: Database pascal2012 (folder JPEGImages) not found in /path/to/pascal2012/
WARNING: Database SBD (folder images) not found in /path/to/SBD/
WARNING: Database COCO (folder images) not found in /path/to/COCO/
-- You can disable this warning in install.m --
-- Successful installation of MCG. Enjoy! --
Warning: The temporary variable im will be cleared at the beginning of each iteration of the parfor loop.
Any value assigned to it before the loop will be lost.  If im is used before it is assigned in the parfor loop, a runtime error will occur.
See Parallel for Loops in MATLAB, "Temporary Variables".
> In run_ucm (line 22)
Starting parallel pool (parpool) using the 'local' profile ... connected to 12 workers.
1 of 3
err
2 of 3
err
3 of 3
Analyzing and transferring files to the workers ...done.
1 of 3
err
2 of 3
err
3 of 3
Error using im2ucm (line 39)
An UndefinedFunction error was thrown on the workers for 'loadvar'.  This might be because the file containing 'loadvar' is not accessible on the workers.  Use addAttachedFiles(pool, files) to specify the
required files to be attached.  See the documentation for 'parallel.Pool/addAttachedFiles' for more details.

Error in run_ucm (line 22)
parfor i = 1:numel(imname)


Caused by:
    Undefined function 'loadvar' for input arguments of type 'char'.

How to solve this problem?    By the way, does the model (COB) support Windows?

**Comment by jponttuset** [comment]
Are you running "pre-trained"?
Have you tried disabling parallelism?
Not sure if COB would work on Windows, but I wouldn't recommend it.

**Comment by ahappycutedog** [comment]
> 
> 
> Are you running "pre-trained"?
> Have you tried disabling parallelism?
> Not sure if COB would work on Windows, but I wouldn't recommend it.

Yes, i run the pre-trained,  Is this error related to parallelism? How to turn off this parallelism in code？

**Comment by jponttuset** [comment]
parfor --> for
Does the demo run?

**Comment by ahappycutedog** [comment]
> 
> 
> parfor --> for
> Does the demo run?

There are some errors:
WARNING: Database pascal2012 (folder JPEGImages) not found in /path/to/pascal2012/
WARNING: Database SBD (folder images) not found in /path/to/SBD/
WARNING: Database COCO (folder images) not found in /path/to/COCO/
-- You can disable this warning in install.m --
-- Successful installation of MCG. Enjoy! --
1 of 3
err
2 of 3
err
3 of 3
Undefined function or variable 'loadvar'.

Error in im2ucm (line 39)
sf_model = loadvar(fullfile(mcg_root, 'datasets', 'models', 'sf_modelFinal.mat'),'model');

Error in run_ucm (line 33)
        ucms{i} = im2ucm(im,'fast');

**Comment by jponttuset** [comment]
Find where the file loadvar.m is and add it to the path.
Sorry but I cannot give further support at this level.

**Comment by ahappycutedog** [comment]
> 
> 
> Find where the file loadvar.m is and add it to the path.
> Sorry but I cannot give further support at this level.

I know, Thanks very much!  But i hvae run the install.m， i don't have got the loadvar.m，so  I  can't add the loadvar.m to the path.
